framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Habilitar soporte de sesiones
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

# Configuración de CORS utilizando nelmio/cors-bundle
nelmio_cors:
    defaults:
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%'] # Utiliza la variable de entorno CORS_ALLOW_ORIGIN
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/': ~
        
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file